name: phonetics
version: 1.5.0
author: Edwin Bühler <fulnir@gmail.com>
description: Soundex, Double Metaphone and Kölner Phonetik
homepage: https://github.com/Fulnir/dart-phonetics
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  intl: any
  junitconfiguration: any
  logging: any
  unittest: any
