name: dart_phonetic
version: 1.0.0
author: Edwin Bühler <edbuehler@gmail.com>
description: Soundex and Kölner Phonetik
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  intl: any
  junitconfiguration: any
  logging: any
  soundex: any
  unittest: any
